apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- obj.yaml

namePrefix: prefix-

configMapGenerator:
- name: config
  behavior: create
  literals:
  - a=b
  - c=d

generatorOptions:
  disableNameSuffixHash: true
